apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  annotations:
    github.com/project-slug: myorg/myrepo
  description: ''
  name: authorization-server
  tags: []
spec:
  lifecycle: experimental
  owner: dev-team
