apiVersion: backstage.io/v1alpha1
kind: Api
metadata:
  annotations:
    github.com/project-slug: myorg/myrepo
  description: Authorize the user to get a valid access/refresh token
  name: api-authorize-the-user-to-get-a-valid-access-refresh-token
  tags:
  - json/http
spec:
  lifecycle: experimental
  owner: group:dev-team
  system: authorization-server
  type: openapi
