apiVersion: backstage.io/v1alpha1
kind: Api
metadata:
  annotations:
    github.com/project-slug: myorg/myrepo
  description: Makes API calls with validated token
  name: api-makes-api-calls-with-validated-token
  tags:
  - json/http
spec:
  lifecycle: experimental
  owner: group:dev-team
  system: authorization-server
  type: openapi
