C4Container
  Person(person, "Person", "Description of person.")
  System_Boundary(authorizationServer, "Authorization Server, domain: security") {
    Container(publicWebBrowser, "Public Web Browser", "Angular", "A public web browser to access non sensitive backend services")
    Container(platformWebBrowser, "Platform Web Browser", "React", "User uses the platform web browser to maintain the cluster of the services")
    Container(platformWebClient, "Platform Web Client", "Spring Boot", "Internal Web Client for internal users to access more privileged services.")
    Container(apiGateway, "API Gateway", "Kong", "Routes and secures all HTTP traffic for authorization, token validation, and service communication clustered for scalability and reliability")
    Container(tokenValidatorService, "Token Validator Service", "Spring Boot", "Validates tokens for all protected requests [JSON/HTTP]")
    Container(apiService, "API Service", "Spring Boot", "Provide OpenAPI endpoints")
    Container(transactionMonitoringService, "Transaction Monitoring Service", "SpringBoot", "Internal service talking to the API service through the API Gateway and needs a valid token to talk with other services through HTTP calls.")
    Container(clientRegistrator, "Client Registrator", "Spring Boot", "Processes stored kafka client messages and register each of them accordingly")
    ContainerDb(postgresDb, "Postgres database", "PostgreSQL", "Contains users and clients to authenticate person and machines")
    ContainerDb(redisDb, "Redis Database", "Redis", "Contains Access/Refresh tokens for limited time")
    ContainerDb(secretManager, "Secret Manager", "Hashcorp Vault", "Stores secrets for rotating JWT secrets for generating JWT tokens")
    ContainerDb(clientsToBeRegistered, "Clients To Be Registered", "Apache Kafka", "Going through a batch process to register new client credentials")
    Boundary(authorizationService, "Authorization Service") {
      Container(springSecurityBean, "Spring Security Bean", "Spring Service", "Security Bean, to setup the oauth2 server and expose the oauth2 endpoints")
      Container(postgresRepository, "Postgres repository", "Spring Service", "Repository for Postgres call")
    }
  }
  Rel(person, publicWebBrowser, "Person authorizes themselves with authorization code flow", "JSON/HTTP")
  Rel(person, platformWebBrowser, "Makes API calls with valid token", "JSON/HTTP")
  Rel(publicWebBrowser, springSecurityBean, "Exchanges authorization code for access/refresh token and to exchange refresh token for new access token", "JSON/HTTP")
  Rel(platformWebBrowser, platformWebClient, "Authorize themselves with privileged token access through the Platform Web Client", "JSON/HTTP")
  Rel(platformWebClient, apiGateway, "Makes API calls with validated token", "JSON/HTTP")
  Rel(platformWebClient, clientsToBeRegistered, "Stores new clients to be registered", "kafka")
  Rel(platformWebClient, springSecurityBean, "Authorize the user to get a valid access/refresh token", "JSON/HTTP")
  Rel(clientsToBeRegistered, clientRegistrator, "Process stored new clients", "kafka")
  Rel(clientRegistrator, springSecurityBean, "Register new clients over the /register-client endpoint", "JSON/HTTP")
  Rel(postgresRepository, postgresDb, "Authenticates user and if they are able to acquire the specific client scopes", "JDBC")
  Rel(postgresRepository, postgresDb, "Registers clients and stores credentials", "JDBC")
  Rel(postgresRepository, redisDb, "Stores Access/Refresh Token", "RESP")
  Rel(springSecurityBean, secretManager, "Generates token with fetched JWT secret", "HTTPS")
  Rel(apiGateway, tokenValidatorService, "Validate Token", "JSON/HTTP")
  Rel(apiGateway, apiService, "Routes authenticated requests to protected API Service [JSON/HTTP]", "JSON/HTTP")
  Rel(tokenValidatorService, redisDb, "Checks that token is not invalidated", "RESP")
  Rel(tokenValidatorService, secretManager, "Validates Token with help of JWT secret", "HTTPS")
  Rel(transactionMonitoringService, springSecurityBean, "Authorize themselves through client credentials token flow", "JSON/HTTP")
  Rel(springSecurityBean, postgresRepository, "Uses", "Internal")
