apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    github.com/project-slug: myorg/myrepo
  description: Authorizez the person/system based on Oauth2 protocol based on /authorize,
    /token, /revoke, /register-client, /introspect
  name: authorization-service
  tags:
  - spring-service
spec:
  dependsOn:
  - resource:postgres-database
  - resource:redis-database
  - resource:secret-manager
  lifecycle: experimental
  owner: group:dev-team
  providesApis:
  - api:api-exchanges-authorization-code-for-access-refresh-token-and-to-exchange-refresh-token-for-new-access-token
  - api:api-authorize-themselves-through-client-credentials-token-flow
  - api:api-register-new-clients-over-the-register-client-endpoint
  - api:api-authorize-the-user-to-get-a-valid-access-refresh-token
  system: authorization-server
  technology: Spring Boot Service
  type: service
