apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    github.com/project-slug: myorg/myrepo
  description: Repository for Postgres call
  name: postgres-repository
  tags:
  - spring-library
  - spring-data
  - database-library
  - authorization-service-library
spec:
  dependsOn:
  - resource:postgres-database
  - resource:redis-database
  lifecycle: experimental
  owner: group:dev-team
  system: authorization-server
  technology: Spring Data JPA
  type: library
