apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    github.com/project-slug: myorg/myrepo
  description: Validates tokens for all protected requests [JSON/HTTP]
  name: token-validator-service
  tags:
  - spring-service
spec:
  dependsOn:
  - resource:redis-database
  - resource:secret-manager
  lifecycle: experimental
  owner: group:dev-team
  providesApis:
  - api:api-validate-token
  system: authorization-server
  technology: Spring Boot Service
  type: service
