apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    github.com/project-slug: myorg/myrepo
  description: Internal service talking to the API service through the API Gateway
    and needs a valid token to talk with other services through HTTP calls.
  name: transaction-monitoring-service
  tags:
  - spring-service
spec:
  consumesApis:
  - api:api-authorize-themselves-through-client-credentials-token-flow
  lifecycle: experimental
  owner: group:dev-team
  system: authorization-server
  technology: Spring Boot Service
  type: service
