apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  annotations:
    github.com/project-slug: myorg/myrepo
  description: Stores secrets for rotating JWT secrets for generating JWT tokens
  name: secret-manager
  tags:
  - hashcorp vault
spec:
  lifecycle: experimental
  owner: dev-team
  system: authorization-server
  technology: hashcorp vault
  type: key-vault
