name: Convert and Validate SVG to XML and YAML

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - closed

jobs:
  convert-and-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Backup catalog files from current branch
        run: |
          make backup-catalogs

      - name: Clean Workspace
        run: |
          make clean

      - name: Convert SVG to XML
        run: |
          make convert-drawio-svg-to-xml

      - name: Convert XML to Backstage YAML
        run: |
          make convert-xml-to-backstage-files

      - name: Compare generated Backstage files with committed Backstage files
        run: |
          make validate-catalogs

      - name: Lint Backstage YAML Files
        run: |
          make lint-backstage-files
